### ISSUE TITLE
Setting page header to routable: false results an exception for corresponding feed

### ISSUE THREAD

**Issue by ichik** [getgrav/grav-plugin-feed#4]
I really think this should be a possible usage. I have a special feed page that I would like to keep hidden from visitors and only its RSS feed to be accessible.

**Comment by rhukster** [comment]
`routable: false` for any page mean you can't reach it in a browser.  As a feed **must** be accessed via a browser, this is expected behavior.  

Grav feeds work by basically viewing the current page with an alternative template (.rss.html or .atom.html twig files).  I guess you could remove the (.html.twig) and make it hidden from the menu and it would not be accessible other than via the feed urls

**Comment by ichik** [comment]
Well, hiding it from the menu isn't a problem, of course. And I don't really think a lot of visitors would find that URL. Still feels weird though.
