### ISSUE TITLE
redirect_default_route breaks the plugin

### ISSUE THREAD

**Issue by hexplor** [getgrav/grav-plugin-feed#44]
```  redirect_default_route: true``` in system.yaml break the plugin completely. If set to false, plugin is back to life :)

**Comment by bartoszwanot** [comment]
Would be nice to have it fixed :)

**Comment by hexplor** [comment]
any chance @rhukster ?

**Comment by rhukster** [comment]
i have this on my list of things to look at.. just focusing on getting 1.6 released at the moment.

**Comment by rhukster** [comment]
I've looked into this and it's tricky.  The main problem is that `redirect_default_route` is doing what you are asking to do .. when you request `/blog.rss` and you are on the homepage `/`.. even though `/blog` is the actual page, the default route is `/`.

The quick fix is to manually create the RSS feed buttons or change the path so that you go to `/.rss` or `/.atom`, etc.  This actually does work although it looks pretty crappy.

**Comment by rhukster** [comment]
Actually have a fix that is going out in next release that will make this work by allowing `/blog.rss` to redirect to `/.rss` and work.. even though it looks crap :)

**Comment by hexplor** [comment]
Small change:
```
<link rel="alternate" type="application/atom+xml" title="My Feed" href="{{ base_url }}/.atom" />
<link rel="alternate" type="application/rss+xml" title="My Feed" href="{{ base_url }}/.rss" />
<link rel="alternate" type="application/json" title="My Feed" href="{{ base_url }}/.json" />
```

**Comment by rhukster** [comment]
That works for you at the root, but non-root based feeds will just use the `{{ base_url }}/my-route.rss` type url.  This is really an implementation detail, not something that can be fixed in feeds itself.
