### ISSUE TITLE
Set the url for the feed manually

### ISSUE THREAD

**Issue by Algram** [getgrav/grav-plugin-feed#9]
I have the domain http://blog.rphl.io .
My content is called "blog" aswell. Now the feed url looks weird (http://blog.rphl.io/blog.rss).

It would be nice to have the option of manually setting a url for the feed.

**Comment by rhukster** [comment]
You can't really change the `blog.rss` part because Grav is just serving the `/blog` route with an `.rss.twig` template (ie as XML).  

However, you could easily add an alias in the `site.yaml` or you could do it also via `.htacess`, so going to `http://blog.rphi.io/feed.rss` goes to the same route.
